-- Application baseline, adapted from the measured draft. Auth is deferred.
-- Timestamps are Unix seconds; media bytes live in object storage.
-- Public IDs are randomly generated by the application, not access controls.

CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL COLLATE NOCASE UNIQUE,
    display_name TEXT NOT NULL,
    bio TEXT NOT NULL DEFAULT '',
    avatar_asset_id INTEGER REFERENCES media_assets(id),
    created_visibility TEXT NOT NULL DEFAULT 'public'
        CHECK (created_visibility IN ('public', 'friends', 'private')),
    liked_visibility TEXT NOT NULL DEFAULT 'friends'
        CHECK (liked_visibility IN ('public', 'friends', 'private')),
    friends_visibility TEXT NOT NULL DEFAULT 'friends'
        CHECK (friends_visibility IN ('public', 'friends', 'private')),
    theme TEXT NOT NULL DEFAULT 'system' CHECK (theme IN ('system', 'light', 'dark')),
    created_at INTEGER NOT NULL
);

CREATE TABLE media_assets (
    id INTEGER PRIMARY KEY,
    owner_id INTEGER NOT NULL REFERENCES users(id),
    object_key TEXT NOT NULL UNIQUE,
    thumbnail_key TEXT,
    mime_type TEXT NOT NULL,
    byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
    width INTEGER NOT NULL CHECK (width > 0),
    height INTEGER NOT NULL CHECK (height > 0),
    created_at INTEGER NOT NULL
);
CREATE INDEX media_assets_owner ON media_assets(owner_id);

CREATE TABLE templates (
    id INTEGER PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE,
    owner_id INTEGER NOT NULL REFERENCES users(id),
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    visibility TEXT NOT NULL DEFAULT 'public'
        CHECK (visibility IN ('public', 'unlisted', 'password')),
    password_hash TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    -- Derived caches, maintained by application batches/jobs, never authoritative.
    list_count INTEGER NOT NULL DEFAULT 0 CHECK (list_count >= 0),
    view_count INTEGER NOT NULL DEFAULT 0 CHECK (view_count >= 0),
    unique_view_count INTEGER NOT NULL DEFAULT 0 CHECK (unique_view_count >= 0),
    popularity_score REAL NOT NULL DEFAULT 0,
    popularity_updated_at INTEGER,
    CHECK ((visibility = 'password' AND password_hash IS NOT NULL)
        OR (visibility <> 'password' AND password_hash IS NULL))
);
CREATE INDEX templates_owner_created ON templates(owner_id, created_at DESC, id DESC);
CREATE INDEX templates_discovery ON templates(popularity_score DESC, id DESC)
    WHERE visibility = 'public';

-- Template structure is fixed after first use in this draft. Labels/tiers/items
-- must be versioned before supporting structural edits to an already-used template.
CREATE TABLE template_tiers (
    template_id INTEGER NOT NULL REFERENCES templates(id),
    tier_index INTEGER NOT NULL CHECK (tier_index >= 0),
    label TEXT NOT NULL,
    color TEXT NOT NULL,
    PRIMARY KEY (template_id, tier_index)
) WITHOUT ROWID;

CREATE TABLE template_items (
    template_id INTEGER NOT NULL REFERENCES templates(id),
    item_id INTEGER NOT NULL CHECK (item_id >= 0),
    asset_id INTEGER NOT NULL REFERENCES media_assets(id),
    label TEXT NOT NULL,
    pool_position INTEGER NOT NULL CHECK (pool_position >= 0),
    PRIMARY KEY (template_id, item_id),
    UNIQUE (template_id, pool_position)
) WITHOUT ROWID;
CREATE INDEX template_items_asset ON template_items(asset_id);

CREATE TABLE tier_lists (
    id INTEGER PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE,
    template_id INTEGER NOT NULL REFERENCES templates(id),
    owner_id INTEGER NOT NULL REFERENCES users(id),
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    preview_asset_id INTEGER REFERENCES media_assets(id),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    like_count INTEGER NOT NULL DEFAULT 0 CHECK (like_count >= 0),
    view_count INTEGER NOT NULL DEFAULT 0 CHECK (view_count >= 0),
    unique_view_count INTEGER NOT NULL DEFAULT 0 CHECK (unique_view_count >= 0),
    UNIQUE (id, template_id)
);
CREATE INDEX tier_lists_template ON tier_lists(template_id, status, created_at DESC, id DESC);
CREATE INDEX tier_lists_owner_created ON tier_lists(owner_id, status, created_at DESC, id DESC);
CREATE INDEX tier_lists_owner_likes ON tier_lists(owner_id, like_count DESC, id DESC)
    WHERE status = 'published';

CREATE TABLE placements (
    list_id INTEGER NOT NULL,
    template_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    tier_index INTEGER CHECK (tier_index >= 0), -- NULL = unranked pool
    position INTEGER NOT NULL CHECK (position >= 0),
    PRIMARY KEY (list_id, item_id),
    FOREIGN KEY (list_id, template_id) REFERENCES tier_lists(id, template_id),
    FOREIGN KEY (template_id, item_id) REFERENCES template_items(template_id, item_id),
    FOREIGN KEY (template_id, tier_index) REFERENCES template_tiers(template_id, tier_index)
) WITHOUT ROWID;
CREATE UNIQUE INDEX placements_slot ON placements(list_id, COALESCE(tier_index, -1), position);
CREATE INDEX placements_consensus ON placements(template_id, item_id, tier_index, list_id);

CREATE TABLE likes (
    list_id INTEGER NOT NULL REFERENCES tier_lists(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    created_at INTEGER NOT NULL,
    PRIMARY KEY (list_id, user_id)
) WITHOUT ROWID;
CREATE INDEX likes_user_created ON likes(user_id, created_at DESC, list_id);

-- Canonical pair permits exactly one relationship, regardless of request direction.
CREATE TABLE friendships (
    user_low_id INTEGER NOT NULL REFERENCES users(id),
    user_high_id INTEGER NOT NULL REFERENCES users(id),
    requested_by INTEGER NOT NULL REFERENCES users(id),
    status TEXT NOT NULL CHECK (status IN ('pending', 'accepted')),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    PRIMARY KEY (user_low_id, user_high_id),
    CHECK (user_low_id < user_high_id),
    CHECK (requested_by IN (user_low_id, user_high_id))
) WITHOUT ROWID;
CREATE INDEX friendships_high ON friendships(user_high_id, status, user_low_id);

-- Exact lifetime deduplication of stored identifiers, NOT of human beings.
-- Application computes a stable opaque 128-bit identifier (no raw IP addresses).
-- Insert-on-conflict-do-nothing; increment unique counters only on successful insert.
CREATE TABLE list_viewers (
    list_id INTEGER NOT NULL REFERENCES tier_lists(id),
    viewer_key BLOB NOT NULL CHECK (length(viewer_key) = 16),
    first_seen_at INTEGER NOT NULL,
    PRIMARY KEY (list_id, viewer_key)
) WITHOUT ROWID;
-- No timestamp index: this draft retains lifetime viewer records.

-- Rebuildable cache. Weighting/eligibility rules must be agreed before writing it.
CREATE TABLE consensus_items (
    template_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    weighted_position_sum REAL NOT NULL DEFAULT 0,
    weight_sum REAL NOT NULL DEFAULT 0 CHECK (weight_sum >= 0),
    contributor_count INTEGER NOT NULL DEFAULT 0 CHECK (contributor_count >= 0),
    updated_at INTEGER NOT NULL,
    PRIMARY KEY (template_id, item_id),
    FOREIGN KEY (template_id, item_id) REFERENCES template_items(template_id, item_id)
) WITHOUT ROWID;
